# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0002_auto_20180414_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoodboundaries',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
