# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0003_auto_20180414_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoodboundaries',
            name='maplabel',
            field=models.CharField(max_length=75),
        ),
    ]
