# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 05:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('tract', models.CharField(max_length=50)),
                ('tract_no', models.IntegerField()),
                ('bg', models.CharField(max_length=50)),
                ('trbg', models.CharField(max_length=50)),
                ('fips', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pop10', models.IntegerField()),
                ('du10', models.IntegerField()),
                ('vac10', models.IntegerField()),
                ('white', models.IntegerField()),
                ('black', models.IntegerField()),
                ('aian', models.IntegerField()),
                ('asian', models.IntegerField()),
                ('nhpi', models.IntegerField()),
                ('other_race', models.IntegerField()),
                ('pop_2_race', models.IntegerField()),
                ('hispanic', models.IntegerField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
